### ISSUE TITLE
Warning: Invalid DOM property `class`. Did you mean `className`?

### ISSUE THREAD

**Issue by ragingwind** [riiid/qtikit#9]
Some of HTML element has own class property but it's not for React.

```
react-dom.development.js:67 Warning: Invalid DOM property `class`. Did you mean `className`?
    at blockquote
    at object
    at ObjectHtml (http://localhost:6006/main.5007cae79afd190272fe.hot-update.js:40:19)
    at div
    at QtiViewer (http://localhost:6006/main.iframe.bundle.js:346:71)
    at unboundStoryFn (http://localhost:6006/vendors~main.iframe.bundle.js:15895:12)
    at ErrorBoundary (http://localhost:6006/vendors~main.iframe.bundle.js:12841:5)
```

**Comment by Il9** [comment]
hmmm...
I can't find anything other than just replacing it.

**Comment by ragingwind** [comment]
Error: Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

TextEntryInteraction
